import sokobanLevelBib

""" Spiel-Settings """
FENSTERBREITE = 1000
FENSTERHOEHE = 800
ANZAHLREIHEN = 15
ANZAHLSPALTEN = 15
SCHWIERIGKEIT = -1000
FELDNUMMER = 0


VORGEFERTIGTESLEVEL = sokobanLevelBib.beispielLevel

LEVEL = VORGEFERTIGTESLEVEL

