import sokobanLevelBib

""" Spiel-Settings """
FENSTERBREITE = 1000
FENSTERHOEHE = 800
ANZAHLREIHEN = 15
ANZAHLSPALTEN = 15
SCHWIERIGKEIT = -1000
einFeldKI = 0
zweiFeldKI = (0, 2)


VORGEFERTIGTESLEVEL = sokobanLevelBib.anderesLevel

LEVEL = VORGEFERTIGTESLEVEL

